services:
  - type: web
    name: job-intelligence-backend
    env: python
    rootDir: .
    buildCommand: python --version && pip --version && pip install -r requirements.txt && python -m playwright install chromium
    startCommand: python -m alembic -c alembic.ini upgrade head && uvicorn app.main:app --app-dir backend --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: AI_MODEL
        value: llama-3.1-8b-instant
      - key: QUEUE_ENABLED
        value: "true"
      - key: QUEUE_NAME
        value: default
      - key: REDIS_URL
        fromService:
          type: redis
          name: job-intelligence-redis
          property: connectionString
  - type: worker
    name: job-intelligence-worker
    env: python
    rootDir: .
    buildCommand: python --version && pip --version && pip install -r requirements.txt && python -m playwright install chromium
    startCommand: PYTHONPATH=backend python -m app.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: AI_MODEL
        value: llama-3.1-8b-instant
      - key: QUEUE_ENABLED
        value: "true"
      - key: QUEUE_NAME
        value: default
      - key: REDIS_URL
        fromService:
          type: redis
          name: job-intelligence-redis
          property: connectionString
  - type: redis
    name: job-intelligence-redis
    ipAllowList: []
